import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Creative Culture",
  description: "Generated by Creative Culture Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased scrollbar-hidden">
        {children}
      </body>
    </html>
  );
}
